### PR TITLE
Ubuntu 24.04 image creation

### PR DESCRIPTION
**Pull request by stephgosling**
Hello!

This adds support for Ubuntu 24.04 (Noble Numbat). It is almost entirely a copy/paste of Jammy; apart from a trivial case change in around efibootgmr and a divergence since 22.04 about if/when the installer runs update-grub2

### CODE REVIEW

**Comment by bahamat** [comment]
We have a branch we're working on for a spring image release (but, we might end up with an early summer release instead). This is basically identical for the ubuntu-24 part, but I was missing the update-grub2 part, which I hadn't had a chance to debug yet. I'll make sure that you get a Co-authored-by credit on the final commit.

**Comment by stephgosling** [comment]
Hi Brianna :rainbow_flag: 

absolutely do try the build with and without that update-grub2 ansible task because I'm new and I don't trust my local environment yet (i.e. did I mess up and does the canonical build environment behave differently) and this was as much a learning exercise as anything else.

From a readability PoV it should possibly go as a last step in the install proper rather than a packer/ansible customisation but I don't think the installer will do the right thing if it's before the reboot. aka I don't think I documented it well enough. Maybe I'm being fussy.

**Comment by bahamat** [comment]
Yeah, it does. I took that task and added it to my in-progress branch, and it worked. My original build from about a month ago had broken networking due to the stale nocloud setting. I haven't had time to go in and debug it yet, but with the additional task, networking gets configured properly, so this has been more helpful than you realize!

As far as being part of the user-script, or ansible...it doesn't much matter in this case. I probably would have put it in ansible myself, so I think it's just fine as-is.

I have a pre-release image up here that you can test:

* https://us-central.manta.mnx.io/bbennett/public/images/ubuntu-24.04-20240606.json
* https://us-central.manta.mnx.io/bbennett/public/images/ubuntu-24.04-20240606.x86_64.zfs.gz

**Comment by teutat3s** [comment]
Changing the SSH port is currently not working as expected after Ubuntu [switched to socket-based activation](https://discourse.ubuntu.com/t/sshd-now-uses-socket-based-activation-ubuntu-22-10-and-later/30189) for the SSH service. I created a [bug report](https://bugs.launchpad.net/ubuntu/+source/openssh/+bug/2069041) for this.

There's also `/etc/ssh/sshd_config.d/50-cloud-init.conf` which we might want to remove from the image to avoid unexpected overrides of `/etc/ssh/sshd_config`.

```
sudo cat /etc/ssh/sshd_config.d/50-cloud-init.conf
PasswordAuthentication yes
```

Should we consider changing back to the "old" way of running SSH on Ubuntu while they investigate the bug?
```
systemctl disable --now ssh.socket
rm -f /etc/systemd/system/ssh.service.d/00-socket.conf
rm -f /etc/systemd/system/ssh.socket.d/addresses.conf
systemctl daemon-reload
systemctl enable --now ssh.service
```

**Comment by bahamat** [comment]
Well, we need `PasswordAuthentication yes`, and it's far better to do it this way. It lets us make the necessary change without needing to maintain the whole file and allows the system to update the system config without wiping out our changes. If users want it configured a different way, or they're concerned about unexpected overrides, they can remove it themselves.

But I do agree that we should revert the listening behavior of sshd. Maybe this makes sense for a container, but we're making HVM images here, and 3MiB isn't going to make or break a system.

**Comment by bahamat** [comment]
Merged in #18.

**Pull request closed without merging**
